spring.application.name=chatbot

# Railway MySQL
spring.datasource.url=${MYSQL_PUBLIC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# Groq API
groq.api.key=${GROQ_API_KEY}